name: 'Publish FoundryVTT Package'
description: 'Publish a FoundryVTT package using the Package Release API'
branding :
  icon : 'box'
  color : 'orange'
inputs:
  package-token:
    description: 'The secret token of your package for the FoundryVTT Package Release API'
    required: true
  manifest-url:
    description: 'The URL of the JSON manifest of your package'
    required: true
outputs:
  response-code:
    description: 'The HTTP response code'
    value: ${{ steps.publish.outputs.response-code }}
  response-json:
    description: 'The JSON response from the Package Release API'
    value: ${{ steps.publish.outputs.response-json }}
runs:
  using: 'composite'
  steps:
  - id: 'publish'
    run: 'python ${{ github.action_path }}/publish.py "${{ inputs.package-token }}" "${{ inputs.manifest-url }}" >> "$GITHUB_OUTPUT"'
    shell: 'bash'
