name: Test The Action
on:
  workflow_dispatch:
    inputs:
      package-token:
        description: 'The FoundryVTT package token'
        default: 'abcdefg123456'
        required: true
        type: string
      module-json-url:
        description: 'The URL of the module.json'
        default: 'https://example.com/module.json'
        required: true
        type: string
jobs:
  package-release-test:
    runs-on: ubuntu-latest
    outputs:
      response-code: ${{ steps.action-test.outputs.response-code }}
      result: ${{ steps.step2.action-test.outputs.result }}
    steps:
    - id: checkout
      uses: actions/checkout@v4
    - id: action-test
      uses: ./
      with:
        package-token: ${{ inputs.package-token }}
        module-json-url: ${{ inputs.module-json-url }}
  output:
    runs-on: ubuntu-latest
    needs: package-release-test
    steps:
    - name: action-output
      run: |
        echo HTTP Response: ${{ needs.package-release-test.outputs.response-code }}
        echo Result: ${{ needs.package-release-test.outputs.result }}
